// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"transactions_routine/api/handlers"
	"transactions_routine/api/services"
	"transactions_routine/config"
	"transactions_routine/database"
	"transactions_routine/database/models"
)

// Injectors from wire.go:

func BuildDependencies() (*Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	db, err := database.NewDB(configConfig)
	if err != nil {
		return nil, err
	}
	account := models.NewAccount()
	accountService := services.NewAccountService(db, account)
	accountHandler := handlers.NewAccountHandler(accountService)
	transaction := models.NewTransaction()
	transactionService := services.NewTransactionService(db, transaction)
	transactionHandler := handlers.NewTransactionHandler(transactionService)
	operationType := models.NewOperationType()
	operationService := services.NewOperationService(db, operationType)
	operationHandler := handlers.NewOperationHandler(operationService)
	server := NewServer(accountHandler, transactionHandler, operationHandler)
	return server, nil
}
